data_config:
  dataset_name: glue

federated_config:
  clients_num: 100
  rounds: 100
  alpha: 1.0
  sample: 0.1

model_config:
  model_type: bert
  permutation_layers: false
  client_model_layers: [0,1,2]
  server_model_layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  model_output_mode: seq_classification
  train_layer_num: 3
  choose_type: random

training_config:
  per_device_train_batch_size: 32
  num_train_epochs: 1
  learning_rate: 5e-5
  metric_name: glue

